name: publish

env:
   NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on: 
  workflow_dispatch:
    branches:
      - 'master'
    working-directory: 
      - './' 
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
          registry-url: 'https://npm.pkg.github.com'

      - name: Install Dependencies
        run: |
          echo "registry=https://registry.npmjs.org"  > .npmrc
        env:
          GITHUB_PAT: ${{ secrets.REPO_READ_PAT }}

      - name: add Dependencies 
        run: echo "always-auth=false"  > .npmrc
      
      - name: install node_modules
        run: npm install
      
      - name: publish
        run: npx can-npm-publish --verbose && npm publish || echo "No need to publish"
        env:
         NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: set version to env
        run: node -p -e '`VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

      - name: add version tag
        uses: pkgdeps/git-tag-action@v2
        with:
         version: ${{ env.VERSION }}
         github_token: ${{ secrets.GITHUB_TOKEN }}
         github_repo: ${{ github.repository }}
         git_commit_sha: ${{ github.sha }}
         git_tag_prefix: "v"
      
    